### PR TITLE
- VCPKG using manifest file

### PR DESCRIPTION
**Pull request by DudeMcDude**
## Description
- Fixed libiconv usage - newer version changed dll name
- Added manifest file for VCPKG, pinned versions to current latest (in case stuff like the above happens again)

## Checklist

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] I used the same coding style as the surrounding code 
- [x] I have tested the proposed changes
- [ ] I extended the documentation, if necessary
- [ ] The proposed change builds also on our build bots (check after submission)

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
All the commented stuff should be removed instead. To recache, try commenting out the vcpkg line under `cache:` (we will reinstate it later). And thanks for putting the manifest in the right place. :)

**Comment by lynxlynxlynx** [comment]
It got killed for taking over an hour. There is a var that could help with priming the cache, but it wouldn't help here, so I think we have to temporarily avoid the main build. So I suggest you uncomment the APPVEYOR_SAVE_CACHE_ON_ERROR line and just `exit 1` (or whatever the powershell version is) in before_build. The build will fail, but the cache will be primed, so then we can remove the hack and the whole thing should build in time.

**Comment by DudeMcDude** [comment]
Oh, it looks like caching doesn't work for PRs (sensibly).  
https://www.appveyor.com/docs/build-cache/#saveupdate-cache-before-build-finishes

So I suppose we'll try it out in a branch?

**Comment by lynxlynxlynx** [comment]
I'll just merge and then you can retry after that fails.

**Comment by lynxlynxlynx** [comment]
Oh and please add -q to the pull invocation, so it won't spam the log so much.

**Comment by lynxlynxlynx** [comment]
Ufff, that was close. But we have the primed caches now. :)

**Pull request merged**
