### PR TITLE
pst/GUIREC: Handle saving of TNO level in the correct Stat

### PR DESCRIPTION
**Pull request by chilvence**
This commit was actually meant to be the last part of #1021 and the handling of each different class level for TNO, but got left out before that was merged.

I was just going bundle it with #1023 at first, but since I'll be rethinking the weapon proficiency handling and that part of GUIREC in general, I've split it out from there so that it doesn't end up getting lost.

## Checklist

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] I used the same coding style as the surrounding code 
- [x] I have tested the proposed changes
- [ ] I extended the documentation, if necessary
- [ ] The proposed change builds also on our build bots (check after submission)

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
There's a bunch of other good stuff in that PR, so this is a weird choice.

**Comment by chilvence** [comment]
I still have a ton more to come, I am just breaking it into small parts instead of sending one huge PR.

Basically I did a load of work on the completely unimplemented stuff over the week I was on holiday in october, but the weapon proficiencies and the XP stuff from the last PR were the only things I didn't get time to scrutinise that deeply.

**Comment by lynxlynxlynx** [comment]
Why not include the table and specifics fixes?

**Comment by chilvence** [comment]
I can do, but they only fix part of the proficiency problem, and since I don't know quite yet what I'll end up with, I thought it better to roll them up with the next set of fixes that revolve around the same theme.

I wont be getting rid of any of that in any case, just putting it on ice for a few days.

**Pull request merged**
