### PR TITLE
(V4) Improve formation movement and right-click moves in general

### PR DESCRIPTION
**Pull request by bernds**
## Description
Version 4 of the formation and general movement improvements.

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
Thanks. You know you can just force-push to the same branch and github will take care of everything? No need to open new PRs.

**Comment by bernds** [comment]
I know I can force-push somehow, but I always thought it was bad practice. If Github can deal with it in a  pull request I might try that next time.

**Comment by lynxlynxlynx** [comment]
You just add -f: `git push -f`. It's bad practice if it's done to a branch that others rely on, since it rewrites history, but for PRs this is not a problem.

**Comment by bradallred** [comment]
thank you sir!

**Pull request merged**
