### PR TITLE
Fix animation of IWD2 orcs conjuring spells

### PR DESCRIPTION
**Pull request by MarcelHB**
## Description
See #2156, orc is back and looks like in the original now (slightly focused posture).

## Checklist

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] I used the same coding style as the surrounding code 
- [x] I have tested the proposed changes
- [x] I extended the documentation, if necessary
- [ ] The proposed change builds also on our build bots (check after submission)

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
Is using animation type 16 not correct?

**Comment by MarcelHB** [comment]
16 makes the orc fall to the ground :)

**Comment by lynxlynxlynx** [comment]
I mean in avatars.2da, not the stance override:
```
diff --git a/gemrb/unhardcoded/iwd2/avatars.2da b/gemrb/unhardcoded/iwd2/avatars.2da
index a972e9af2..574df003f 100644
--- a/gemrb/unhardcoded/iwd2/avatars.2da
+++ b/gemrb/unhardcoded/iwd2/avatars.2da
@@ -361,8 +361,8 @@
 0xE7C9     MABW       MABW       MABW       MABW       9          2          1          *
 0xE7E8     MSCR       MSCR       MSCR       MSCR       9          2          1          *
 0xE7F9     MUM2       MUM2       MUM2       MUM2       9          2          1          *
-0xE800     MOR1       MOR1       MOR1       MOR1       9          2          1          *
-0xE818     MOR1       MOR1       MOR1       MOR1       9          2          1          *
+0xE800     MOR1       MOR1       MOR1       MOR1       16         2          1          *
+0xE818     MOR1       MOR1       MOR1       MOR1       16         2          1          *
 0xE808     MOR6       MOR6       MOR6       MOR6       9          2          1          *
 0xE810     MOR2       MOR2       MOR2       MOR2       16         2          1          *
 0xE822     MOR2       MOR2       MOR2       MOR2       16         2          1          *
```

**Comment by MarcelHB** [comment]
What am I supposed to look at? They both seem to work and I don't spot any apparent difference.

**Comment by lynxlynxlynx** [comment]
If this fixes the bug, it's preferred, since it's the base data. But I now see it does have A2, so it wouldn't fit perfectly. So the exception approach will do for now.

**Pull request merged**
