### PR TITLE
Making Windows compile again

### PR DESCRIPTION
**Pull request by MarcelHB**
## Description
Bring Windows back to the game. #1389 

## Checklist

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] I used the same coding style as the surrounding code 
- [x] I have tested the proposed changes
- [x] I extended the documentation, if necessary
- [ ] The proposed change builds also on our build bots (check after submission)

### CODE REVIEW

**Comment by MarcelHB** [comment]
I just want to whether everything else and AppVeyor/MSVC builds. Still working on GCC as discussed in #1389

**Comment by lynxlynxlynx** [comment]
Looks good so far and hopefully msvc's diagnostic is a bit more useful to you.

**Comment by MarcelHB** [comment]
@bradallred Can you maybe take a look at MSVC errors? To me, it even looks valid since I don't see how https://github.com/gemrb/gemrb/blob/078f266ca8ea56b394f4d268e39a74a769fe8239/gemrb/core/Plugin.h#L90

ever gets a non-abstract plugin type. And then again, `GetImporter` (as in `DialogHandler.cpp`) -> ... -> `MakePluginHolder` makes me think that this `MakeHolder<IMPORTER>()` should not be there like this, and just have the holder injected.

**Comment by bradallred** [comment]
when do you ever see `IMPORTER` passed as an _abstract_ type? the only uses are `AREImporter`, `BAMImporter`, `CHUImporter`, `CREImporter`, `DLGImporter`, `GAMImporter`, and `ITMImporter` which are all concrete.

**Comment by MarcelHB** [comment]
From what I see, if you follow this line for example https://github.com/gemrb/gemrb/blob/078f266ca8ea56b394f4d268e39a74a769fe8239/gemrb/core/DialogHandler.cpp#L110

You end up in something that is this:
```cpp
PluginHolder<ImporterPlugin<DialogMgr>> MakeImporterPluginHolder(PluginID id) {
	return MakePluginHolder<ImporterPlugin<DialogMgr>>(id);
}
```
here at:
https://github.com/gemrb/gemrb/blob/078f266ca8ea56b394f4d268e39a74a769fe8239/gemrb/core/PluginMgr.h#L144-L147

**Comment by bradallred** [comment]
> Looking at this statically, there is a reason to complain then.

which is?

**Comment by MarcelHB** [comment]
The compiler then is probably seeing an attemp to do this:
```cpp
class GEM_EXPORT ImporterPlugin final : public Plugin
{
	Holder<DialogMgr> importer = MakeHolder<DialogMgr>();
```
and this:
```cpp
inline Holder<DialogMgr> MakeHolder( ) noexcept
{
	return Holder<DialogMgr>(new DialogMgr());
}
```
And since `DialogMgr` is abstract, there is the respective error.

**Comment by bradallred** [comment]
the definition of `MakePluginHolder` is nothing more than a cast. There is no object construction. how does MSVC implement `std::static_ptr_cast` thats all we are trying to do here.

https://github.com/gemrb/gemrb/blob/078f266ca8ea56b394f4d268e39a74a769fe8239/gemrb/core/PluginMgr.h#L139-L142

how do you figure

**Comment by MarcelHB** [comment]
Not an invocation, but maybe MSVC is just putting in that type into `T` and discovers an illegal code path? Which then made me wonder if there is something that requires this line at all, given that we ask for a pointer from the plugin manager.

**Comment by bradallred** [comment]
the most straight forward fix (and arguably an upgrade) would be to remove `Held<T>` from the plugin hierarchy and just use `std::shared_ptr` and `std::static_ptr_cast`

**Comment by MarcelHB** [comment]
Ok, feel free to work on it and I'll rebase and continue with the other stuff then. Otherwise I'll try it out tomorrow for myself.

**Comment by bradallred** [comment]
sounds good. can we just merge this now then?

**Pull request merged**
