### PR TITLE
Console colors fix

### PR DESCRIPTION
**Pull request by burner1024**
## Description
unhardcode console colors, fix bg2 party console and dialog color, ref #1982

## Checklist

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] I used the same coding style as the surrounding code 
- [x] I have tested the proposed changes
- [x] I extended the documentation, if necessary
- [x] The proposed change builds also on our build bots (check after submission)

### CODE REVIEW

**Comment by burner1024** [comment]
Captura desde 2024-02-08 23-58-33

Fixed dialog console color. Hopefully without collateral damage...

**Comment by lynxlynxlynx** [comment]
Thanks. I suggest a different name for the colors, so they don't get confused for the actual console colors. Maybe MSG and MSG_PARTY.

Please also add the two new entries to other colors.2da, so the structure remains the same and they don't default to full white. 

The name color fix is a oneliner in `DisplayMessage::GetSpeakerColor` btw.

**Comment by burner1024** [comment]
> Thanks. I suggest a different name for the colors, so they don't get confused for the actual console colors. Maybe MSG and MSG_PARTY.

Maybe straight DISPLAYSTRING + _PARTY? If this 2da is supposed to be self-documenting for modders or something.
Because from the first glance I can't tell what some of those mean, like MAPICNBG or ALTDOOR.

**Comment by lynxlynxlynx** [comment]
DISPLAYSTRING isn't very telling either, since almost all text goes through those functions.

**Comment by burner1024** [comment]
Where'd you get [PST party color](https://github.com/gemrb/gemrb/commit/c75bfb46fcca9dc22aa356d28a81d716e9ec9047#diff-eefe647a01562f0dc95ef8bec8e4f6a1729e3e4e7c2ebe4ad2497c32a54c8222R18)? Looks very similar, maybe I should use that one

**Comment by lynxlynxlynx** [comment]
Same inaccurate color picker approach.

**Comment by burner1024** [comment]
OK, I copied whatever colors there were from DIALOG_* to MSG_* for all games except BG2, where I used the new value for MSG_PARTY.

Captura desde 2024-02-09 07-08-00

**Comment by lynxlynxlynx** [comment]
Thanks!

**Pull request merged**
