### PR TITLE
MSVC build issues

### PR DESCRIPTION
**Pull request by bradallred**
testing changes to reconcile MSVC and GCC

### CODE REVIEW

**Comment by MarcelHB** [comment]
Looks like progress ... https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-error-c2487?view=msvc-170

**Comment by bradallred** [comment]
It looks like none of the plugins are getting linked to core

**Comment by lynxlynxlynx** [comment]
Looks like it's mostly left with symbols we explicitly mark for external linkage.

**Comment by MarcelHB** [comment]
The best thing I got so far is this VS VM image with an awfully bloated, slow, crashy Win11 + Visual Studio 17 setup. On my way to (hopefully) get the linking done, MSVC complains about something I consider valid:
```
E:\gemrb\core\IniSpawn.cpp(209,55): error C2666: '+': 2 overloads have similar conversions [E:\build_msvc\gemrb\core\gemrb_core.vcxproj]
E:\gemrb\core\IniSpawn.cpp(209,55): message : could be 'built-in C++ operator+(bool, int)' [E:\build_msvc\gemrb\core\gemrb_core.vcxproj]
E:\gemrb\core\IniSpawn.cpp(209,55): message : or       'built-in C++ operator+(const char *, __int64)' [E:\build_msvc\gemrb\core\gemrb_core.vcxproj]
E:\gemrb\core\IniSpawn.cpp(209,55): message : while trying to match the argument list '(GemRB::ieVariable, int)' [E:\build_msvc\gemrb\core\gemrb_core.vcxproj]

E:\gemrb\core\IniSpawn.cpp(227,55): error C2666: '+': 2 overloads have similar conversions [E:\build_msvc\gemrb\core\gemrb_core.vcxproj]
E:\gemrb\core\IniSpawn.cpp(227,55): message : could be 'built-in C++ operator+(bool, int)' [E:\build_msvc\gemrb\core\gemrb_core.vcxproj]
E:\gemrb\core\IniSpawn.cpp(227,55): message : or       'built-in C++ operator+(const char *, __int64)' [E:\build_msvc\gemrb\core\gemrb_core.vcxproj]
E:\gemrb\core\IniSpawn.cpp(227,55): message : while trying to match the argument list '(GemRB::ieVariable, int)' [E:\build_msvc\gemrb\core\gemrb_core.vcxproj]

E:\gemrb\core\IniSpawn.cpp(227,102): error C2664: 'void GemRB::SetPointVariable(GemRB::Scriptable *,const char *,const GemRB::Point &,const char *)': cannot convert argument 2 from 'GemRB::Point' to 'const char *' [E:\build_msvc\gemrb\core\gemrb_core.vcxproj]
E:\gemrb\core\IniSpawn.cpp(227,64): message : No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called [E:\build_msvc\gemrb\core\gemrb_core.vcxproj]
E:\gemrb\core\GameScript/GSUtils.h(120,17): message : see declaration of 'GemRB::SetPointVariable' [E:\build_msvc\gemrb\core\gemrb_core.vcxproj]

E:\gemrb\core\IniSpawn.cpp(235,51): error C2666: '+': 2 overloads have similar conversions [E:\build_msvc\gemrb\core\gemrb_core.vcxproj]
E:\gemrb\core\IniSpawn.cpp(235,51): message : could be 'built-in C++ operator+(bool, int)' [E:\build_msvc\gemrb\core\gemrb_core.vcxproj]
E:\gemrb\core\IniSpawn.cpp(235,51): message : or       'built-in C++ operator+(const char *, __int64)' [E:\build_msvc\gemrb\core\gemrb_core.vcxproj]
E:\gemrb\core\IniSpawn.cpp(235,51): message : while trying to match the argument list '(GemRB::ieVariable, int)' [E:\build_msvc\gemrb\core\gemrb_core.vcxproj]

E:\gemrb\core\IniSpawn.cpp(235,100): error C2664: 'void GemRB::SetVariable(GemRB::Scriptable *,const char *,GemRB::ieDword,const char *)': cannot convert argument 2 from 'int' to 'const char *' [E:\build_msvc\gemrb\core\gemrb_core.vcxproj]
E:\gemrb\core\IniSpawn.cpp(235,60): message : Conversion from integral type to pointer type requires reinterpret_cast, C-style cast or function-style cast [E:\build_msvc\gemrb\core\gemrb_core.vcxproj]
```
I'm currently working with appending `.CString()` as workaround, but maybe you have a better preference

**Comment by lynxlynxlynx** [comment]
That or `.begin()`, I'm not sure we have any preference.

**Comment by MarcelHB** [comment]
I found the problem, and again it seems that MSVC is technically correct while MSYS2/GCC simply doesn't care enough.

In the essence, `GEM_EXPORT` is used ambiguously. When building the core, we want the symbols to be exported, and at the users (plugins), we want them for importing. But there, we also have stuff from the core headers with `GEM_EXPORT` that we still want to export at the same time (see such an error in #1552), as the core needs something of them (`ImporterPlugin`, `IndexedArchive`).

So with that PR, everything is exporting but this collides as MSVC prepends `__imp_` for later being used with `__declspec(dllimport)`, and that does not happen anymore. But we also cannot just revert this, as the prev state is also broken, and bad concerning other things.

Options:
1. We manage to clean up these semi-export classes, but I remember trouble so no idea how much it takes.
2. We think of another macro for these cases that indicates always-export. For the template classes, this is probably easy, for these purely virtual base classes ... I don't know, we had trouble with MSVC in the past there.

You see the actual trouble (in AppVeyor) when applying this patch, and also stuff related to `FixedSizeString` that I did not resolve yet:
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 2d3435fe9..6b127a215 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -484,8 +484,6 @@ if (STATIC_LINK)
 		unset(STATIC_LINK CACHE)
 		MESSAGE(STATUS "Static linking not (yet) supported on this platform.")
 	endif (NOT WIN32)
-else ()
-  ADD_DEFINITIONS("-DGEM_BUILD_DLL")
 endif (STATIC_LINK)
 
 INCLUDE_DIRECTORIES(${CMAKE_CURRENT_BINARY_DIR} gemrb/includes gemrb/core platforms/${CMAKE_SYSTEM_NAME})
diff --git a/gemrb/core/CMakeLists.txt b/gemrb/core/CMakeLists.txt
index a71dc7e57..ecc9a08e1 100644
--- a/gemrb/core/CMakeLists.txt
+++ b/gemrb/core/CMakeLists.txt
@@ -139,6 +139,7 @@ ENDIF()
 if (STATIC_LINK)
 	ADD_LIBRARY(gemrb_core STATIC ${gemrb_core_LIB_SRCS})
 else (STATIC_LINK)
+	ADD_DEFINITIONS("-DGEM_BUILD_DLL")
 	ADD_LIBRARY(gemrb_core SHARED ${gemrb_core_LIB_SRCS})
 	TARGET_LINK_LIBRARIES(gemrb_core ${CMAKE_DL_LIBS} ${COREFOUNDATION_LIBRARY} ${ICONV_LIBRARY})
 	IF(WIN32)
```

**Comment by MarcelHB** [comment]
> That or `.begin()`, I'm not sure we have any preference.

I was thinking of fixing `CheckVariable` altogether, but then it's ~120 users plus things down the slope.

**Comment by bradallred** [comment]
> I don't know, we had trouble with MSVC in the past there

it did, but im pretty sure almost all of it was related to MSVC requiring export of the copy/move constructors, so it is generally easily dealt with by `default`ing them. may need to `ifdef` for gcc tho (if something is deleted or a detour is defined)

**Comment by lynxlynxlynx** [comment]
New overloads to fix;
`Actions.cpp(5465,49): error C2666: '+': 2 overloads have similar conversions [C:\projects\gemrb\gemrb\core\gemrb_core.vcxproj]`

**Comment by MarcelHB** [comment]
That was not even a warning for me. Strangely, the [previous build](https://ci.appveyor.com/project/lynxlynxlynx/gemrb/builds/42601770) looks exactly, and acceptable, like my local instance.

**Comment by MarcelHB** [comment]
Damn, I forgot one line clearing the whitespace from the diffs. Will check, although it should not be related to the error above ...

**Comment by MarcelHB** [comment]
That's a little odd, because there are two errors, the 2nd one is:
```
C:\projects\gemrb\gemrb\core\GameScript\Actions.cpp(5465,52): error C2660: 'memcpy': function does not take 2 arguments [C:\projects\gemrb\gemrb\core\gemrb_core.vcxproj]
```
and it's not 5465 but 5467, and also some has messed up this so that MSVC sees only two args:
https://github.com/gemrb/gemrb/blob/541a64653e15008cba9768c64a86ac02323ca8fe/gemrb/core/GameScript/Actions.cpp#L5465-L5467

And my bad, I forgot to include this (but this has no impact on the two above):
```diff
diff --git a/gemrb/core/GUI/ViewInterfaces.h b/gemrb/core/GUI/ViewInterfaces.h
index f70287142..72ab03312 100644
--- a/gemrb/core/GUI/ViewInterfaces.h
+++ b/gemrb/core/GUI/ViewInterfaces.h
@@ -77,8 +77,8 @@ public:

                operator bool() const { return bool(callback); }
        }* executingResponseHandler = nullptr;
-
-       class GEM_EXPORT ActionKey {
+
+       class ActionKey {
                uint32_t key;
        public:
                ActionKey(uint32_t val) : key(val) {}
```

**Comment by lynxlynxlynx** [comment]
It's code that might have been changed before you made your changes, since it's from today / yesterday. I wouldn't worry about memcpy until the first error is fixed.

**Comment by MarcelHB** [comment]
The 1st one is also not fitting in here, and this means that AV attempts to compile something else, i. e. not what the code looks like on `msvc` right now.

**Comment by lynxlynxlynx** [comment]
This branch is not up to date with master, that's all?

**Comment by bradallred** [comment]
Done

**Comment by lynxlynxlynx** [comment]
Awesome, thanks!

**Pull request merged**
