### PR TITLE
subviews: post-merge fixes for Windows

### PR DESCRIPTION
**Pull request by MarcelHB**
There were some refactorings that broke how I made it work on master, so this should do it here.

### CODE REVIEW

**Comment by bradallred** [comment]
Thanks, I can merge it whenever you are ready. Looks like you are still working on it?

**Comment by MarcelHB** [comment]
Yes, wait. I found a runtime problem.

**Comment by MarcelHB** [comment]
Back at working. Could one of you please cherry-pick 52808b198e39f44a9fd78018f00366e821f8bf61 into master? Not sure why it's working quite reliably there but as it no longer does here, it better be fixed like this.

**Comment by lynxlynxlynx** [comment]
Much thanks! I expected there to be more trouble in PluginLoader. :)

**Pull request merged**
