### PR TITLE
Update GUIINV.py

### PR DESCRIPTION
**Pull request by gregariousmonk**
## Description
Added code for GUIINV.py to remediate #1848 for shields to display correctly on HF avatars..  There are other BAMs that use the size N but I didn't find any references to them in the iwd+how game files.

## Checklist

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] I used the same coding style as the surrounding code 
- [x] I have tested the proposed changes
- [ ] I extended the documentation, if necessary
- [ ] The proposed change builds also on our build bots (check after submission)

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
Are there other valid animations with N? IOW should just the pdoll entries be set to M instead?

**Comment by gregariousmonk** [comment]
There are 33 WPN*.BAM animations but it looks as though they were intended to be used for displaying offhand weapons, which aren't used in iwd+how.  

I was cautious about editing the 2da file in case there were scripting dependencies that I'm not aware of, but changing it and doing limited testing gives the same result as the conditional in the script, ie. the shields display correctly on the pdoll.

You folks have a lot of experience with the code, which method do you think would be better?

**Comment by lynxlynxlynx** [comment]
The size column of pdolls.2da is only ever used in GUIINV and since iwd has its own, it's completely safe to just fix the data that we unhardcoded. Please also do the same in the "iwd" copy.

**Comment by gregariousmonk** [comment]
I'm going to close this pull request and open one without the code change file.

**Pull request closed without merging**
