### PR TITLE
Demo: add a start window

### PR DESCRIPTION
**Pull request by m7600**
## Description
This is a modest start window for the demo. Here's a [screenshot](https://raw.githubusercontent.com/m7600/GemRB-demo-extension/main/Screenshot%20from%202020-11-13%2016-49-37.png). 

This pull requests includes:
A background (start.png)
Graphics for a New Game and Quit buttons, in a single file (bstart.bam)
An updated version of Start.py for functionality (It's probably not the most elegant Python code you've seen, but it works)
A new .chu file (guiconn.chu)

EDIT: Whoops, I forgot to list the .chu file. Give me a second... Done.

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
Looks ok, thanks! If you want to improve it, the SetVisible call shouldn't be needed and LoadGame belongs in NewGamePress, which then also means the QuitGame call can be removed.

What did you have in mind for future work? Might be a good idea to sit on this for a while, so it's easier to work.

**Comment by m7600** [comment]
Thanks lynx, I'll make those changes you mentioned. 

Future work: I'm not sure. There's a lot of things that I'd like to add to the demo. I admit that I'm more comfortable making art assets than writing code. I was thinking about making a portrait for the protagonist, and maybe add an NPC, a few enemies, and a new area. What do you think I should focus on?

**Comment by chilvence** [comment]
Oh wow, if you reckon you can make some npc's and enemies, that's the start of a game right there! :)

I've always wanted to do something with this demo if I would ever be able to finish what I can on PST stuff - can't promise much, but can I support you in any way?

**Comment by m7600** [comment]
@chilvence Thanks. Yeah, here's a modest [orc animation](https://raw.githubusercontent.com/m7600/GemRB-demo-extension/main/orc.gif) I made, it kinda sucks, but I can try to improve it. I made it with Blender and Gimp.

**Comment by m7600** [comment]
BTW Planescape: Torment is my favorite game

**Comment by chilvence** [comment]
That's a really nice start, model actually looks pretty good, I wouldn't say it sucks. If I were to criticise I would just say the animation could be more fluid.

I know hand animation is a really tricky skill though, cos I tried it once upon a time...

**Comment by lynxlynxlynx** [comment]
Oh, you can also add another label and then `Label.SetText(GemRB.Version)`, which will do the obvious thing. Or change the existing ones to include the version.

The overall bug for this is #313. 

What I think is needed most, since it's probably the hardest to do, but you actually know how, is more character animations. Ideally we'd have at least a documented process if not an automated workflow to export from Blender (for all the required orientations, correct camera angle, scale and all stances) and perhaps a good starting project file for further creation. iesh can be used to automate stitching into bams. I don't know which animation type you used for the orc, but there are several choices.

Don't think about combat yet: that will require quite some work, since most of the data is stubbed. Neutral NPCs are fine though.

Btw, I've already committed the bg for the interior area, but so far I haven't managed to make the WED for it successfully, so that's why it's not in yet. Currently I have time just for quick diversions, but that should change in a few weeks. But even then, if I get some proper time, I try to work on polishing subviews, so it's best also for me if you focus on content. The windowing code will need to be updated after the merge anyway, so let's deal with new gui stuff last.

**Comment by m7600** [comment]
@chilvence Thanks for the feedback, I agree

@lynxlynxlynx Ok, I'll make some character animations then. I'll have to make them pre-shaded until we can figure out the issue of the clown colors, or do you prefer that I give them clown colors? I can make some monsters like giant spiders, goblins, orcs, etc. For the automated part in Blender, I use a Python script that was written by Clint Bellanger in his FLARE project, here's [his tutorial with the Python code](http://clintbellanger.net/articles/isometric_tiles/). 
I'll take a look at the interior area, maybe I can make the WED file and make it work using a combination of DLTCEP and IE Tileset Map Editor.

**Comment by m7600** [comment]
BTW lynx I looked at the TODO for the demo and it says that the searchmap should be improved, but I think that has already been fixed, right? I'm asking because the protagon doesn't seem to be able to walk through the pillars anymore.

**Comment by chilvence** [comment]
Heartily agree on the need for automated workflow, some sort of glue between Blender and Iesh that anyone can use. I actually feel a sense of dread when thinking about making a character sprite, which is not an ideal feeling :)

I haven't used Blender for a long time, but from what I know of it, it's quite capable of doing the sprite exporting legwork. It's iesh that I have never really used, I always rely on NearInfinity to look at stuff

Shall I open a tracker issue to carry on this train of thought? I mean, I'm hearing the corn whisper "if you build it, they will come" right now...

**Comment by lynxlynxlynx** [comment]
searchmap: yes, it's stale and should be removed from the list.

nice that that flare script is in python — makes it easier to fix (missing and excessive orientations) and integrate with our tools — iesh's bam_composer in particular. You write a simple project file, run it and it does the magic. Docs:
https://github.com/gemrb/iesh/blob/master/bam_composer
https://github.com/gemrb/iesh/blob/master/infinity/bam_composer.py#L19

chiv: for the workflow? Yes please and feel free to copy over the above.

**Comment by chilvence** [comment]
Ok, I will condense the discussion on that so far and see if I can find anything else useful

**Comment by lynxlynxlynx** [comment]
Oh yeah, forgot to answer one thing: monsters don't need to be clown coloured — they won't be customizable.

**Comment by lynxlynxlynx** [comment]
I've added a new tag for demo/new game reports and filed a few more. You can click on the yellow button to get to the listing.

**Comment by m7600** [comment]
I'll close this pull request for now, if that's ok with you.

**Comment by m7600** [comment]
Testing the new cave area, I'll upload the files soon. 

Screenshot from 2020-11-15 18-18-38

**Comment by lynxlynxlynx** [comment]
I've now added an intro window based on your work. One can skip it via cfg option if desired and it also sports a textedit for the character name.

**Pull request closed without merging**
