### PR TITLE
Subviews Polygon.cpp reversion for #822

### PR DESCRIPTION
**Pull request by chilvence**
This reverts commit 80078c548c448d5518ce78f3da66c9b1183e5a7d.

Related to issue discussion: #822

I can exhaustively test the game areas if need be, but other than whether or not they load, I am not sure what to be testing or looking for?

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
Can you determine which polygon / infopoint this is about? I don't see anyone in ar0600 with a height of 0.

**Comment by bradallred** [comment]
it is the wall polygon at index 286

**Comment by lynxlynxlynx** [comment]
Ah, in the wed then. We should just skip it in the loader.

**Comment by chilvence** [comment]
Does that mean it was the data at fault? Is this reversion still needed or does it just need adding to?

**Comment by bradallred** [comment]
no, we shouldn't revert this. the problem wasn't a case of not enough vector space like initially theorized.

**Comment by lynxlynxlynx** [comment]
Yeah, the data is at fault, so we need to fix this in TISImporter or WEDImporter, wherever we read it in.

**Comment by chilvence** [comment]
No problem, glad the culprit has been pinned down all the same

**Pull request closed without merging**
