### PR TITLE
Rest of VCPKG PR

### PR DESCRIPTION
**Pull request by DudeMcDude**
## Description
Continuing #1652 

## Checklist

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] I used the same coding style as the surrounding code 
- [ ] I have tested the proposed changes
- [ ] I extended the documentation, if necessary
- [ ] The proposed change builds also on our build bots (check after submission)

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
Thanks!

**Comment by DudeMcDude** [comment]
I forgot to comment APPVEYOR_SAVE_CACHE_ON_ERROR...

Also for some reason it looks like it stopped using the cache on the commit right after that one. Wonder why that is...

**Comment by lynxlynxlynx** [comment]
That's odd indeed. It used the cache in the subsequent PR, but never in the main branch.
One thing we didn't pin was the vcpkg version itself. Let's always grab the same release tag / commit, so there won't be any surprises.

**Comment by lynxlynxlynx** [comment]
Bleh, another cycle. It used the cache in 6434b6cda89fc2, but merging your PRs again skipped it — 447cdc2644a.
It looks like the cancelled builds cause it: https://ci.appveyor.com/project/lynxlynxlynx/gemrb/builds/44275180
We use rolling builds not to be too much of a burden.

It's now clear how to fix this — indeed we can't keep APPVEYOR_SAVE_CACHE_ON_ERROR enabled all the time.

**Pull request merged**
