### PR TITLE
Reverb refactor

### PR DESCRIPTION
**Pull request by bradallred**
I dug up my old stash for #1402 and resolved all the conflicts. I still need to find an OpenAL library that supports EFX to test it. I think thats the only reason it sat collecting dust. From what I can tell it looks fine.

### CODE REVIEW

**Comment by MarcelHB** [comment]
What about https://openal-soft.org/?

**Comment by lynxlynxlynx** [comment]
See hoops we jump through to get the brew version working on the build bot: .github/workflows/builder.yml
Should be transferable to xcode.

**Comment by lynxlynxlynx** [comment]
LGTM, but haven't tried yet.

**Comment by lynxlynxlynx** [comment]
@MarcelHB do you remember any good test cases?

**Comment by MarcelHB** [comment]
Nothing in particular, I'd need to dig through the map settings as well. Irenicus' dungeon always had notable acoustics though.

**Comment by lynxlynxlynx** [comment]
I'm not sure I could tell the difference tbh.

**Comment by MarcelHB** [comment]
I'll have a look, or ear, at it later today.

**Comment by MarcelHB** [comment]
Sounds good again. Compared with master and original.

**Comment by lynxlynxlynx** [comment]
Thanks for verifying!

**Pull request merged**
