### PR TITLE
[demo] fixed some of the animations for the protagonist

### PR DESCRIPTION
**Pull request by m7600**
## Description
Fixed some of the animations for the protagonist, see [this discussion](https://github.com/gemrb/gemrb-assets/pull/1)

Some notes:
The [cast and conjure](https://github.com/gemrb/gemrb/blob/2515887fcdbd6929ff3ef8903f5e209fdbcfb33d/gemrb/core/CharAnimations.cpp#L1941-L1950) animations have the same suffix "ca" but different cycles, I don't know what to do here, so I only added a new file for conjure (with 9 empty cycles). The new file is ZHMW1CA.

[Damage](https://github.com/gemrb/gemrb/blob/2515887fcdbd6929ff3ef8903f5e209fdbcfb33d/gemrb/core/CharAnimations.cpp#L1952-L1956) seems to be the same thing as "get hit" (old: ZHMW1GH), the new file is ZHMW1G14.

"Die" and "Sleep" have been updated to the new format, with their corresponding empty cycles.

[Twitch and sleep](https://github.com/gemrb/gemrb/blob/2515887fcdbd6929ff3ef8903f5e209fdbcfb33d/gemrb/core/CharAnimations.cpp#L2004-L2014) have the exact same code, even the same suffix and number of cycles. I don't know if this is intentional or not. So I only included a new file for Sleep, ZHMW1G16

"Ready" (g1) has been copied from "standing", adding empty cycles (G11).

Some animations cannot be implemented due to a lack of code, for example:
[Emerge](https://github.com/gemrb/gemrb/blob/2515887fcdbd6929ff3ef8903f5e209fdbcfb33d/gemrb/core/CharAnimations.cpp#L1966)
[Get Up](https://github.com/gemrb/gemrb/blob/2515887fcdbd6929ff3ef8903f5e209fdbcfb33d/gemrb/core/CharAnimations.cpp#L1965)
[Hide](https://github.com/gemrb/gemrb/blob/2515887fcdbd6929ff3ef8903f5e209fdbcfb33d/gemrb/core/CharAnimations.cpp#L1985)

A1 to A8 don't seem to require an update, since they don't use empty cycles.

I don't know what ZHMW1SP is supposed to be. The animation seems weird, it looks like some sort of dance. Maybe it's some kind of spell animation.

I hope I haven't missed anything.

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
Excellent, thanks!

cast: this is the start of the casting animation (hand waving) that then loops as needed
conjure: this is the end of the animation, the final delivery (for example a push)
So the casting cycles need at least to be duplicated, so something is displayed.

twitch: great catch! Checked the bg2 cimt2g16 and you're right, same thing. Will remove the code duplication.

**Comment by m7600** [comment]
Ok, I'll fix the cast/conjure animation.

I just checked cimt2g16 from BG2:EE. You know what's really weird about these animations in the official games? Not only do they have a lot of empty cycles, but also each of those cycles has a bunch of empty frames. And not only at the beginning, but also at the end. Cimt2g16 has a total of 99 cycles, but only nine of them have graphics. It has 846 frames, most of those are empty. I wonder why they did this. There has to be a reason. Anyway, I'll write tomorrow when I get more stuff done.

**Comment by lynxlynxlynx** [comment]
Yeah, the gaps are weird. Not all cycles have 99 frames either. I guess it somehow made some lookup math easier for them. Or it's some kind of speed optimization.

**Comment by m7600** [comment]
I just checked the different .bam files for ZHMW1, there's no animation for hand waving (cast), only for conjure.

**Comment by lynxlynxlynx** [comment]
Then it's fine to copy the cycles.

**Comment by lynxlynxlynx** [comment]
Do you plan to finish this? Looks like only the cast cycles need to be added still.

**Comment by m7600** [comment]
Yes, sorry about the delay. I'll get to it later today, in a few hours.

**Comment by m7600** [comment]
I don't know how to edit this pull request to add the new file, so I made a separate pull request #1212

**Comment by MarcelHB** [comment]
You can always continue committing and pushing, the PR isn't freezing anything.

**Comment by lynxlynxlynx** [comment]
I'll do it manually, the other one targetted the wrong branch as well.

**Comment by lynxlynxlynx** [comment]
Thanks!

**Comment by m7600** [comment]
Ah, so that was the problem, I was trying to commit it to the wrong branch. Lesson learned.

**Pull request closed without merging**
