### PR TITLE
IWD1 - Spell overlays: only Insect Plague visible on invisible enemies...

### PR DESCRIPTION
**Pull request by caillean7**
... like tested on the original.

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
Thanks!

**Comment by bradallred** [comment]
is there a reason we haven't merged this?

**Comment by lynxlynxlynx** [comment]
It didn't work for her, I have to recheck here and potentially dive in.

**Comment by lynxlynxlynx** [comment]
Fixed the problem in the code and applied. :)

**Pull request merged**
