### PR TITLE
Moved a GUIFactory.h #include to appease Visual Studio

### LINKED ISSUE #766: Subviews & MSVC:  "Use of undefined type GemRB::GUIFactory"
This error is really confusing me because I can't understand why it happens with Visual Studio and not GCC

The following files fail to build with the same error ```C2027, Use of undefined type GemRB::GUIFactory (Holder.h Line 76)```

```Animations,cpp, Calendar.cpp, AnimationFactory.cpp, Core.cppm ControlAnimation.cpp, DialogHandler.cpp, DisplayMessage.cpp```

```FAILED: gemrb/core/CMakeFiles/gemrb_core.dir/Animation.cpp.obj 
  B:\VS\VC\Tools\MSVC\14.26.28801\bin\HostX64\x64\cl.exe  /nologo /TP -DGEM_BUILD_DLL -DHAVE_CONFIG_H -Dgemrb_core_EXPORTS -I. -I..\..\..\gemrb\includes -I..\..\..\gemrb\core /DWIN32 /D_WINDOWS /W3 /GR /EHsc /MD /Zi /O2 /Ob1 /DNDEBUG /showIncludes /Fogemrb\core\CMakeFiles\gemrb_core.dir\Animation.cpp.obj /Fdgemrb\core\CMakeFiles\gemrb_core.dir\ /FS -c ..\..\..\gemrb\core\Animation.cpp
B:\msvc\src\chiv\gemrb\core\Holder.h(76): error C2027: use of undefined type 'GemRB::GUIFactory'
  B:\msvc\src\chiv\gemrb\core\Interface.h(78): note: see declaration of 'GemRB::GUIFactory'
  B:\msvc\src\chiv\gemrb\core\Holder.h(72): note: while compiling class template member function 'GemRB::Holder<GemRB::GUIFactory>::Holder(const GemRB::Holder<GemRB::GUIFactory> &)'
  B:\msvc\src\chiv\gemrb\core\Interface.h(819): note: see reference to function template instantiation 'GemRB::Holder<GemRB::GUIFactory>::Holder(const GemRB::Holder<GemRB::GUIFactory> &)' being compiled
  B:\msvc\src\chiv\gemrb\core\Interface.h(335): note: see reference to class template instantiation 'GemRB::Holder<GemRB::GUIFactory>' being compiled
```

To work around this, I looked for where Interface.h was including "Holder.h" and added an include for GUI/GUIFactory.h just before it, and then all those files build.

I just don't know if this is right or not, since there is too much stuff happening here that I don't understand. I did manage to run the game and walk around/use the gui though. (that is, after hacking around the final issue I had)

### PR DESCRIPTION
**Pull request by chilvence**
One more complaint from Visual Studio's compiler.

One less thing stopping subviews from building on VS2019.

This is all that was needed to close  #766 

## Checklist

- [x] Commit messages are descriptive and explain the rationale for changes
- [ ] I used the same coding style as the surrounding code [ no actual code here]
- [x] I have tested the proposed changes
- [ ] I extended the documentation, if necessary
- [ ] The proposed change builds also on our build bots (check after submission)

### CODE REVIEW

**Comment by chilvence** [comment]
It looks like the buildbots fail to build this 

https://travis-ci.org/github/gemrb/gemrb/jobs/692860358#L1314

**Comment by MarcelHB** [comment]
I had that locally on subviews some minutes ago, but then I rebuild with `-DSDL_BACKEND=SDL2` as this refers to SDL1.2. So this should not be linked to this particular PR.

**Comment by chilvence** [comment]
I was hoping so, but I thought it best to make sure.

I still can't believe I didn't have anything like this amount of trouble just building with MSYS/MinGW. Do you stumble across weird stuff like this much?

**Comment by MarcelHB** [comment]
Not so much, since I doubt that MinGW/MSYS touch the GCC core a lot, the non-platform specific parts are consistent, and maybe just need an minor change on a newer version. 

It's probably you because you are the only one (we know of) working on MSVC on both branches right now, and in the years before, nobody did. :wink:

**Comment by chilvence** [comment]
It's because I am an expert at finding the path of most resistance :)

I kind of have to, in a strange way, or I'm not likely to learn about anything. They don't teach any of this stuff at catering school :)

**Comment by bradallred** [comment]
thanks!

**Pull request merged**
