### PR TITLE
AREImporter: dropping an assertion

### PR DESCRIPTION
**Pull request by MarcelHB**
## Description
See #1882.

## Checklist

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] I used the same coding style as the surrounding code 
- [x] I have tested the proposed changes
- [x] I extended the documentation, if necessary
- [ ] The proposed change builds also on our build bots (check after submission)

### CODE REVIEW

**Comment by bradallred** [comment]
this doesn't address my comment:
https://github.com/gemrb/gemrb/issues/1882#issuecomment-1677932178

so what is the extra data? is it just padding or what?

**Comment by lynxlynxlynx** [comment]
Same 0xff values like the rest of the block

**Comment by bradallred** [comment]
so why are we sure that we don't have a bug in our understanding of `Map::FogMapSize`? PST uses `GFFlags::SMALL_FOG`, but maybe it's a per area thing.

we should at least look at the value of `TMap->XCellCount` and `TMap->YCellCount` and see what that would produce without `SMALL_FOG`. 60 bytes is a lot more than any padding should introduce.

**Comment by lynxlynxlynx** [comment]
The buggy state is unreproducable both in the original and gemrb, so I don't know why you're so adamant.

**Comment by bradallred** [comment]
Because, if it's not reproducible then what is the point of removing the assert? As I said it's there for a reason.

**Comment by MarcelHB** [comment]
Savegames don't run but we have no idea where this comes from and how to reproduce -- and having this removed, there is no apparent side-effect so far.

**Comment by bradallred** [comment]
I understand removing it wont cause a problem other than using the wrong size for a fog tile. It sounds like a corrupt save game if it's not reproducible. What is the save date on the game? Maybe it corresponds to some relevant refactoring.

if its not corruption, then it feels like we are just hiding something we don't understand. Maybe some graphics setting affects it.

**Comment by lynxlynxlynx** [comment]
PST doesn't store real time in the save, so we can't be sure. Best approximation would be mtime/ctime of the file on Marcel's disk. It's at least 2019 or older though, since the bug in #163 is visible in the thumbnail.

I now suspect it's a gemrb save, since NI doesn't display the journal.

**Comment by bradallred** [comment]
ok, then one last issue:
```
ieDword mapSize = ieDword(map->ExploredBitmap.Bytes());
assert(ExploredBitmapSize <= mapSize);
mapSize = std::min(mapSize, ExploredBitmapSize);
str->Seek(ExploredBitmapOffset, GEM_STREAM_START);
str->Read(map->ExploredBitmap.begin(), mapSize);
```

seems like the data is supposed to contain `ExploredBitmapSize`. We aren't skipping the possible remainder. I'm supposing this is ok? it seems like this is the last bit of data read so it doesn't matter.

if thats true, then just go ahead and merge it I guess.

**Comment by lynxlynxlynx** [comment]
We seek when reading the next structure (WEDImporter::GetWallGroups), since there's no guarantee that they would be in order or packed tightly.

**Pull request merged**
