### PR TITLE
[demo] Add a minimap for the cave area 

### PR DESCRIPTION
**Pull request by m7600**
This commit adds a minimap for the demo's cave area, see #1210. The .mos file was made with DLTCEP.

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
Thanks! This supplements the files in #1070. Can you make the searchmap as well (I did it with DLTCEP)? Then we have all the basics for adding the area.

**Comment by m7600** [comment]
I'm trying to make it following [this tutorial](http://www.simpilot.net/~sc/dltcep/areamaking/main.htm#overlay), but something goes wrong and I don't know how to fix it. I'll attach the screenshot showing the problem. I'll try doing this with IETME instead of DLTCEP.

Screenshot from 2021-04-03 17-07-43

**Comment by m7600** [comment]
Nevermind, I found out what the problem was, the frame count was wrong. OK, I'll keep using DLTCEP for this.

**Comment by lynxlynxlynx** [comment]
You can look at the one of the outside area, to get the correct number for walls (I don't remember off the top of my head).

**Comment by m7600** [comment]
Yes, I'm trying to set it up for the flood fill now. Also known as "Left-click Hell".

Screenshot from 2021-04-03 17-22-50

**Comment by lynxlynxlynx** [comment]
That doesn't look that good though. Near the bookcase, there's too much ground marked as 4 (assuming it means wall) and the same for the opposite walls that are "tilted" away from the viewer — only its base needs to be inaccessible, the hidden part marked as a wall. The bookcases will need the same approach.

Some things are easier to fixed before the fill, since the bg is more visible, so it's worth it to make the outlines good from the start.

**Comment by m7600** [comment]
4 represents the floor in this case. 0 would be the impassable sections. It's possible to toggle between them in DLTCEP. But yeah, I'll try to make it as clean as possible. One thing that I'm not entirely convinced of is the speed of this workflow. It may be faster with IETME, I'll have to do some tests.

Screenshot from 2021-04-03 20-10-11

Screenshot from 2021-04-03 20-09-56

**Comment by m7600** [comment]
Ok, I updated the pull request. DLTCEP crashed while I was using it, but I managed to make the search map before it crashed. It's a black and blue .bmp file. It's not perfect, but it's a start.

**Comment by lynxlynxlynx** [comment]
Cool, thanks! Can you teleport to the area? I get crashes, looks like because the searchmap and tilemap (TIS) sizes are different. Please attach the latest TIS and WED.

**Comment by m7600** [comment]
When I use mta("ar0110"), I'm getting some serious crashes here as well, and possibly also a memory leak, since my computer starts processing like crazy and everything freezes, I have to actually press the power off button to stop it. I tried this with the latest TIS and WED files, also with the old ones, and I even made everything from scratch again with IETME, it seems to be the same crash in each case. This may have something to do with subviews. I've updated the PR with the new files that you requested.

**Comment by lynxlynxlynx** [comment]
Thanks, I'll check them out. In the meantime I've added an assert, so the crash will always happen at the same place and not write to random memory.

**Comment by lynxlynxlynx** [comment]
Your files worked fine for me, coupled with my previous changes. :) Added a bunch of other basic stuff. Now you can travel inside and out or cheat your way in by rightclicking on the map icon.

**Comment by m7600** [comment]
Awesome, thanks! I just tested it. The search map definitely needs some refinement, but it's good to see that the cave area is now part of the demo.

**Pull request closed without merging**
