### PR TITLE
windows: fetch opengl, try building it on appveyor

### PR DESCRIPTION
**Pull request by lynxlynxlynx**
Blind try for #1671

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
Oh wow, look at all the choices :)
```
[SDL 2 Driver/DEBUG]: Render driver count: 5
[SDL 2 Driver/DEBUG]: Driver 4 named software
[SDL 2 Driver/DEBUG]: Driver 3 named opengles2
[SDL 2 Driver/DEBUG]: Driver 2 named opengl
[SDL 2 Driver/DEBUG]: Driver 1 named direct3d11
[SDL 2 Driver/DEBUG]: Driver 0 named direct3d
```

**Comment by MarcelHB** [comment]
Hate to disappoint you, but this is a compile-time information: https://github.com/zielmicha/SDL2/blob/373232d63fffdca74fffefab97c5e455576fbb91/src/render/SDL_render.c#L47-L79

**Comment by MarcelHB** [comment]
Hate to disappoint you, but this is a compile-time composition: https://github.com/libsdl-org/SDL/blob/17b329d199899da4bc328632f852e3c96f98c665/src/render/SDL_render.c#L92 + https://github.com/libsdl-org/SDL/blob/17b329d199899da4bc328632f852e3c96f98c665/src/render/SDL_render.c#L661

**Comment by lynxlynxlynx** [comment]
No matter, we are looking for the opengl one anyway. -1 doesn't cut it in this case.

**Comment by lynxlynxlynx** [comment]
Hmm, now it fails with a permission error before even reaching the new code (or the log is buffered and we just don't see). @DudeMcDude can you try building with this PR applied and enabling opengl?

**Comment by bradallred** [comment]
> or the log is buffered and we just don't see

yeah, it _is_ on another thread, so that can happen, but if the process is exiting without crashing all pending messages should have been written and flushed...

**Comment by DudeMcDude** [comment]
> Hmm, now it fails with a permission error before even reaching the new code (or the log is buffered and we just don't see). @DudeMcDude can you try building with this PR applied and enabling opengl?

opengles matches "opengl" pattern :)
Other than that seems to work (launched demo at least after fixing that).

**Comment by lynxlynxlynx** [comment]
Ah, good catch, thanks!

**Comment by lynxlynxlynx** [comment]
Didn't help for the test, so I guess it's just a limitation of the VM. It would be bad to disable the test, but we can compromise: build opengl only for tags and not test, while the rest remain using software rendering and do run the test. Would also mean we'd have pretty much identical builds around release time for both video drivers.

**Comment by lynxlynxlynx** [comment]
Hmm, so it doesn't like something else — the last build was without opengl and the same testing regimen.

**Comment by lynxlynxlynx** [comment]
Ah, I see it now, we still force opengl, doh.

**Comment by lynxlynxlynx** [comment]
So now it's confirmed that SDL's solution (at least in 2.0.22) isn't enough or the renderer is bad:
```
[SDL 2 Driver]: Creating display: opengl
[SDL 2 GL Driver/FATAL]: OpenGL backend must be used instead of direct3d
[SDL20Video/DEBUG]: Renderer: direct3d
```
Looking at the code it means it failed to create the renderer internally and then fell back to -1 behaviour:
https://github.com/libsdl-org/SDL/blob/main/src/render/SDL_render.c#L972
Which explains why the bot didn't like when we forced opengl. So it's all clear. :)

**Comment by lynxlynxlynx** [comment]
fix gl env var sharing — we shouldn't be testing in gl mode

**Pull request closed without merging**
