### PR TITLE
Subviews

### PR DESCRIPTION
**Pull request by bradallred**
## Description
Subviews merge

## Checklist

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] I used the same coding style as the surrounding code 
- [ ] I have tested the proposed changes
- [ ] I extended the documentation, if necessary
- [ ] The proposed change builds also on our build bots (check after submission)

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
Ah, I thought you'd just do it, but let's wait for the bots then, since they started.

**Comment by lynxlynxlynx** [comment]
All good! The style one is too much to bother and has problems master as well, so let's just ignore that and leave it for enforcement in #161 .

**Comment by bradallred** [comment]
any preference on the merge style? just a standard merge commit?

**Comment by lynxlynxlynx** [comment]
I'd go for that or a rebase, yeah. Rebasing should have nicer results, but I fear it would cause tons of merge conflicts. I'll go give it a test try locally. 

Squashing would super simplify the history, but we'd lose a lot of information as well.

**Comment by lynxlynxlynx** [comment]
Yeah, terrible. It breaks on the first commit. While `-X theirs` gets farther, it's not by much, so I didn't even inspect it.

**Comment by bradallred** [comment]
so standard merge commit?

**Comment by lynxlynxlynx** [comment]
Yep!

**Comment by lynxlynxlynx** [comment]
Let's keep the branch around for any separate bisections.

**Pull request merged**
