### PR TITLE
Fixed the artifacts / stray pixels in scrlbar1.bam

### PR DESCRIPTION
**Pull request by m7600**
Fixed the artifacts / stray pixels in scrlbar1.bam with BamWorkshop 2.

### CODE REVIEW

**Comment by m7600** [comment]
Lynx I fixed the problem of the artifacts / stray pixels in the scrollbar.

**Comment by lynxlynxlynx** [comment]
Is the transparency still ok?

**Comment by m7600** [comment]
I think so. Here's a [screenshot](https://raw.githubusercontent.com/m7600/GemRB-demo-extension/main/Screenshot%20from%202020-11-09%2018-48-46.png). On another note, I'm working on the fog of war as well. Right now I'm using the one from IW2 as a reference, but obviously I won't use that file, instead I'll make a new one from scratch.

**Comment by lynxlynxlynx** [comment]
Cool, thanks!

**Pull request merged**
