### PR TITLE
Fix biography selection.

### PR DESCRIPTION
**Pull request by kindaro**
Fixes issue #655.

### CODE REVIEW

**Comment by kindaro** [comment]
This may be the shortest patch I shall ever propose. Why was that `+1` there in the first place?

**Comment by lynxlynxlynx** [comment]
You can look at git blame output. Does this work for all the npcs? Eg. also Ignus, Vhailor.

**Comment by kindaro** [comment]
I do not have saves with all of them, only The Nameless One, Morte and Dak'kon, but all three are now correct.

**Comment by lynxlynxlynx** [comment]
Yep, works for everyone, thanks. :)

**Pull request merged**
