### PR TITLE
Compiler flags testing fixed

### PR DESCRIPTION
**Pull request by czarny247**
## Checklist

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] I used the same coding style as the surrounding code 
- [x] I have tested the proposed changes
- [x] I extended the documentation, if necessary
- [ ] The proposed change builds also on our build bots (check after submission)

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
It doesn't appear to be good enough. You can still see -fsigned-char and -ffast-math failing everywhere and it's not like they're new flags that only fresh compilers would support. Before we were adding all three unconditionally.

I think the dashes remain the same problem, just that it's now the second one.

**Comment by bcmhercun** [comment]
> It doesn't appear to be good enough. You can still see -fsigned-char and -ffast-math failing everywhere and it's not like they're new flags that only fresh compilers would support. Before we were adding all three unconditionally.
> 
> I think the dashes remain the same problem, just that it's now the second one.

Yes, it looks like no dashes/hyphens are allowed in variable names: https://stackoverflow.com/questions/50423280/cmake-indicates-compiler-does-not-support-flag-but-it-does

Removed all of them.

**Comment by bradallred** [comment]
I don't know if it's a problem or not, but I always write it `IF(HAS_FLAG)` instead of `IF("${HAS_FLAG}")`. I'm not sure how an empty string evaluates in cmake.

**Comment by lynxlynxlynx** [comment]
Please just sanitize it completely, so it doesn't break later with some other problematic char. I suggest turning anything not in [:alnum:] into an underscore.

**Comment by lynxlynxlynx** [comment]
Thanks!

**Pull request merged**
