### PR TITLE
Add PYTHON_VERSION configure option

### PR DESCRIPTION
**Pull request by h3xx**
Allows one to request a specific Python version to link against using `-DPYTHON_VERSION=3`. Defaults to `Auto` which means to try 2.3, then 3, then fail, which is what it does currently.

**Does not change the default behavior if this option is not specified.**

### CODE REVIEW

**Comment by h3xx** [comment]
> Let's take the opportunity and default to version 3 though. We might have a minimum requirement on 3.2 like many others, but I don't know and it doesn't really matter.

@lynxlynxlynx Good idea -- Python 2 *is* EOL since April 2020, so it makes sense to let it go.

Unfortunately, I just tried compiling gemrb against Python 3, and it's giving me errors. Working on a fix for a FTBFS right now.

**Comment by lynxlynxlynx** [comment]
Yeah, it was just reported — is it the same as #1405?

**Comment by h3xx** [comment]
@lynxlynxlynx Yes, that's the same issue I ran into. I have a fix that at least fixes the compile issue here: https://github.com/h3xx/gemrb/commits/fix-python3-type-error

**Comment by lynxlynxlynx** [comment]
Please open a separate PR for that then. I suspect it won't build on py2, but the bots will test that for us.

**Comment by h3xx** [comment]
Added #1407.

This PR (i.e. the page you're on, #1406) should be ready to merge as it doesn't change anything except give you the option to try compiling it against Python 3.

**Comment by lynxlynxlynx** [comment]
I still think switching the default is a good idea, but I haven't thought about the build bots. We do plan to switch the bots over to py3 by default in this cycle as well (#1285), but until we fix the last known issue of broken state fonts, that's not going to happen. So it'd be pointless to now force py2 just to revert that later. So yeah, all good.

**Pull request merged**
