### PR TITLE
Use fmt for logging

### PR DESCRIPTION
**Pull request by lynxlynxlynx**
#1527

There's only one notable difference that I noticed — fmt doesn't can't handle displaying null pointers, but besides the audio driver (workaround included), I've not hit that anywhere.

### CODE REVIEW

**Comment by bradallred** [comment]
> fmt doesn't can't handle displaying null pointers

this certainly makes sense for an automatic (`{}`) format since it would dereference the pointer, but I would think you could specify something like `{:p}` to have it print at least the address.

**Comment by lynxlynxlynx** [comment]
We'll just have to be a bit more careful, since I guess p would always print the address, which we never need.

**Comment by bradallred** [comment]
if you're talking about cstrings, then we just keep on weeding them out over time :)

**Comment by lynxlynxlynx** [comment]
It was from openal, so not within our powers. :)

**Comment by lynxlynxlynx** [comment]
Eh, should have merged sooner. Will push manually once I resolve.

**Pull request closed without merging**
