### PR TITLE
Fix lost data on string convertion

### PR DESCRIPTION
**Pull request by Dreamkins**
## Description
Issue https://github.com/gemrb/gemrb/issues/1937

This fixes all the problems. I couldn't think of anything better, but it works.

### CODE REVIEW

**Comment by bradallred** [comment]
I can’t examine the code because I’m on mobile, but this doesn’t seem like the correct fix. PyStringAsStringView should just return a StringView.On Nov 26, 2023, at 08:23, sonarcloud[bot] ***@***.***> wrote:﻿
Kudos, SonarCloud Quality Gate passed!    
  0 Bugs
  0 Vulnerabilities
  0 Security Hotspots
  0 Code Smells
 No Coverage information
 0.0% Duplication

**Comment by Dreamkins** [comment]
> I can’t examine the code because I’m on mobile, but this doesn’t seem like the correct fix. PyStringAsStringView should just return a StringView.>

Look at Issui please

**Comment by lynxlynxlynx** [comment]
I agree, it's an unwieldy fix.  And since there are no known problems with other encodings any more, what @bradallred  suggested is the way to go. The TODO in PyStringAsStringView and PyStringWrapper can also be removed then. It will also enable making that StringView operator explicit.

**Comment by bradallred** [comment]
I did. C++ garantes that temporaries are valid until the end of an expression. Anywhere we are violating that can be addressed by saving the temporary to a variable like you are doing, but you still shouldn’t need to change the conversion operator.We shouldn’t have to make two function calls to get what we need from the PyObject.On Nov 26, 2023, at 08:52, Dreamkins ***@***.***> wrote:﻿

I can’t examine the code because I’m on mobile, but this doesn’t seem like the correct fix. PyStringAsStringView should just return a StringView.>

Look at Issui please

**Comment by Dreamkins** [comment]
In my opinion, the conversion operator is dangerous, since it is easy to pass the result by reference and not notice it. I returned the conversion statement but the additional variables remained to hold the result.

**Comment by bradallred** [comment]
what is the value of your `core->config.SystemEncoding`?

**Comment by Dreamkins** [comment]
> what is the value of your `core->config.SystemEncoding`?
windows-1251

**Comment by Dreamkins** [comment]
> I think we can close this. @Dreamkins is there any remaining issue you are having that this resolves for you?

The journal still doesn't work for me on your fixes.

**Comment by bradallred** [comment]
which of the fixes in this PR are relevant to that?

**Comment by Dreamkins** [comment]
> which of the fixes in this PR are relevant to that? I just fixed another, maybe that was it?

My PR fixes it together with buttons.

**Comment by Dreamkins** [comment]
> that didn't answer the question. Is it working with that last change then?

The buttons work with the latest changes, but the Journal is completely empty.

**Comment by Dreamkins** [comment]
Yes, with the latest changes to the Joutnal it worked!

**Comment by bradallred** [comment]
I've opened a new issue for you. I'm closing this PR. thanks.

**Pull request closed without merging**
