### PR TITLE
Fast-math fix for GCC/Clang

### PR DESCRIPTION
**Pull request by MarcelHB**
See #1790.

## Checklist

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] I used the same coding style as the surrounding code 
- [x] I have tested the proposed changes
- [x] I extended the documentation, if necessary
- [ ] The proposed change builds also on our build bots (check after submission)

### CODE REVIEW

**Comment by bradallred** [comment]
is there not a fix required for MSVC as well?

**Comment by MarcelHB** [comment]
Thought so too but the [docs](https://learn.microsoft.com/en-us/cpp/build/reference/fp-specify-floating-point-behavior) don't show any more sophisticated control.

Best guess is dropping `/fp:fast` from reading what it says but I have no way to check MSVC for either being affected so far or being fixed by some similar measure.

**Comment by bradallred** [comment]
good enough until someone complains or can test it.

**Comment by lynxlynxlynx** [comment]
Actually that's a good point. A user did just complain yesterday. He gets crashes sometimes when scrolling text, also always at the end of chargen. So it could be something like this.

**Comment by MarcelHB** [comment]
Is the user using some AppVeyor nightly, or using MSVC in general? Because v0.9.1 did not have that back then.

**Comment by lynxlynxlynx** [comment]
Latest nightly, but I've asked him to retest with a build from before that change.

**Pull request merged**
