### PR TITLE
[demo] Fixed the rabbit animation orientations

### PR DESCRIPTION
**Pull request by m7600**
Fixed the orientations for the rabbit animations, similar to pull request #1176, discussed in issue #1175.
But I don't know if you want this (because maybe we don't need the extra orientations), so feel free to reject this pull request.

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
Well, since you went through all the work, of course we'll take it. 👍🏾

**Comment by lynxlynxlynx** [comment]
Well, since you went through all the work, of course we'll take it. 👍🏾

**Comment by lynxlynxlynx** [comment]
Thanks!

**Comment by m7600** [comment]
No prob. But it says that it failed to build on Mac OS and ir failed the style checks. I don't know what the style check fail means.

**Comment by lynxlynxlynx** [comment]
Doesn't matter. Everything broke on github for about half an hour.

**Pull request merged**
