### PR TITLE
Three sound improvements

### PR DESCRIPTION
**Pull request by MarcelHB**
## Description
Looking at what has been fixed by 95d258a34a9b98f62f13fb4db325f634aa6ad818 and what was haunting me in https://github.com/gemrb/gemrb/issues/2166, I'd like to propose three sound improvements:

1. Walking sounds were not spatial but were vague all over the map, now they are. Unfortunately they are very loud this way compared to other sounds of the same volume setting. That's why I added some multiplier. Feel free to test and compare to the original.
2. Spatial sounds were not rolling off over distance. Now they do over while not turning fully mute technically (that's also a matter of the OpenAL distance model) but you can now hear things coming close and going away depending on the camera/listener's position. That's way more immersive hearing the enemies finding their way and coming closer. :slightly_smiling_face: 
3. OpenAL mostly doesn't support stereo data being spatialized, so many area affects stay as loud and centered no matter where you are on the map (see annoying thrall invisibility attempts). Now we can have these effects in the same way as everything else, following the official idea: splitting stereo into two mono channels and vector-play them.

Please feel free to test and give some feedback.

## Checklist

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] I used the same coding style as the surrounding code 
- [x] I have tested the proposed changes
- [x] I extended the documentation, if necessary
- [ ] The proposed change builds also on our build bots (check after submission)

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
1. It's odd that this would be needed — we already take `sndchann.2da` factors into account. A further decrease by factors of 0.3 and 0.1 seem wild. 
Looking at iwd2-re, [at least at init](https://github.com/alexbatalov/iwd2-re/blob/4fa36bcd6c33e0d35c9e273561aa683aece88490/src/CBaldurChitin.cpp#L2191), there are no further factors applied to those values. The DirectSound calls [seem to pass negative values](https://github.com/alexbatalov/iwd2-re/blob/4fa36bcd6c33e0d35c9e273561aa683aece88490/src/CSound.cpp#L197) if that was correctly extracted.
Anyway, we could just provide overrides for the table. One or two mods may actually change it, but if even the default isn't working properly, they'd need to provide GemRB-specific tables anyway. So a hard override should be fine.

2. `SetupNewStream` uses quite different values for rolloff, I wonder if we could unify the approach. Ambients are not perfect yet either IIRC.

3. Annoying, but since the result for the user is better, let's go for it.

**Comment by MarcelHB** [comment]
> 1. It's odd that this would be needed — we already take `sndchann.2da` factors into account. A further decrease by factors of 0.3 and 0.1 seem wild.
>        Looking at iwd2-re, [at least at init](https://github.com/alexbatalov/iwd2-re/blob/4fa36bcd6c33e0d35c9e273561aa683aece88490/src/CBaldurChitin.cpp#L2191), there are no further factors applied to those values. The DirectSound calls [seem to pass negative values](https://github.com/alexbatalov/iwd2-re/blob/4fa36bcd6c33e0d35c9e273561aa683aece88490/src/CSound.cpp#L197) if that was correctly extracted.
>        Anyway, we could just provide overrides for the table. One or two mods may actually change it, but if even the default isn't working properly, they'd need to provide GemRB-specific tables anyway. So a hard override should be fine.

Ok, I try the 2DA override approach.

> 2. `SetupNewStream` uses quite different values for rolloff, I wonder if we could unify the approach. Ambients are not perfect yet either IIRC.

That's even more suprising how it has worked so far. Given that you can have one distance model in OAL at the time and ambients  may have range settings. Best explanation seems to be this: https://stackoverflow.com/questions/68726623/java-openal-source-gain-of-zero-after-passing-the-max-distance.

It starts attenuating after ref. distance and stops attenuating after max. distance, leaving the sound at the last non-zero volume then. Roll-off describes the slope. So for what I did here was to have a higher rolloff and high max. distance to push the value towards inaudibility when far away from screen.

The doesn't exactly fit my impression how the ambients actually work (is there some hard distance check somewhere else? Haven't looked for it) but atm I'm not sure how much to unify here.

**Comment by MarcelHB** [comment]
Please look at the 2DA approach.

**Comment by lynxlynxlynx** [comment]
Are you testing with iwd2 or some other game?

**Comment by MarcelHB** [comment]
I've tested IWD2, BG2 (where footsteps are esp. loud) and a bit of PST.

**Comment by lynxlynxlynx** [comment]
They ship different values (iwd2 also has extra columns), so we need to be careful with a single override. BG2 for example already has:

> WALKINGC    25
> WALKINGM    25
> ARMOR       15
So in effect you're making walking sounds louder. IWD2 has them at 70.

**Comment by MarcelHB** [comment]
No, not louder, because maybe the problem is actually something else: BG2's sndchann.2da has 20 channel items whereas we have 24 in the enum. I first copied gemrb/unharcdoded/shared/sndchann.2da and adjusted armor + walksounds down to what I had. It didn't work as expected. Then I added the four missing Char6 to 9 entries and things were good.

So maybe I just fix all these 2DAs?

**Comment by lynxlynxlynx** [comment]
Yeah, `ReadSoundChannelsTable` doesn't do a string lookup, just reads by index. We already use the row name, so it's a simple fix to actually use it for everything. So I think you should fix that first and then recheck if bg2 values need any tweaking at all.

**Comment by MarcelHB** [comment]
Changed the lookup into the name of the 2DA.

**Comment by lynxlynxlynx** [comment]
Perfect, so no extra value tweaking is needed. :)

**Comment by lynxlynxlynx** [comment]
Thanks!

**Pull request merged**
