### PR TITLE
TTFManager: saving the file data stream for later

### PR DESCRIPTION
**Pull request by MarcelHB**
A simple fix suggestion for #1486.

On Windows, I can now see that many glyphs are missing, a very few on Linux. But this is a different story I suppose.

## Checklist

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] I used the same coding style as the surrounding code 
- [x] I have tested the proposed changes
- [x] I extended the documentation, if necessary
- [x] The proposed change builds also on our build bots (check after submission)

### CODE REVIEW

**Comment by bradallred** [comment]
we cant change that `free` to `delete`, that is undefined behavior. we need to match `free` with `calloc` or change to `new`

**Comment by MarcelHB** [comment]
Good idea, time for some C-to-C++ beauty.

**Comment by bradallred** [comment]
doesn't `~TTFFontManager` need to call `close()` then? looks like this potentially leaks if you were to destroy `TTFFontManager` without closing it first.

**Comment by MarcelHB** [comment]
Hm, the resource so far is effectively owned by FT2 that calls static `close` at some point over being given as a function pointer (line 88), I guess somewhere in `FT_Done_Face` that is in the d'tor. But unless we have succesfully created an FT2 face (line 98), we haven't moved away the pointer (line 106). So unless FT2 has taken over, the `ImporterBase` d'tor is doing the job instead.

**Comment by bradallred** [comment]
I meant the non static `TTFFontManager::Close`, which looks like it calls the other along with `FT_Done_Face`. We already call `Close()` at the top of `TTFFontManager::Import` so I dont see why calling it in the destructor as well would be an issue.

**Comment by MarcelHB** [comment]
In `TTFFontManager::Close` it's the `FT_Stream` stream, not the `DataStream` stream. And since `FT_Stream` is `null` at least in the first call on top of `Import`, nothing is happening there, but in the destructor.

I'll check with Valgrind.

**Comment by bradallred** [comment]
then we have more problems. if an object is allocating memory, that memory needs to be freed when the object goes out of scope.

Calling `Close()` in the destructor (or at any other point in the lifecycle) _should not_ cause a problem, Im not making a statement about how things are, I'm suggesting how they should be.

It's also an unpleasant smell if we are leaving memory to be cleaned up at some undetermined period of time beyond the objects lifecycle. I don't even know why we have a static `close()`, the `FT_Stream` is a member of the object, not class. seems like we should just not use `FT_Stream_CloseFunc`

**Comment by MarcelHB** [comment]
Yeah, I'm with you and suspect that there is some not-so-good lifetime management biting us here, also because I now spot gaps in the font use, as if not all glyphs have been extracted.

For now, I just haven't found time to go deeper how exactly a font manager, a font and the Freetype resources are spending their lifetime, or how they are supposed to under the current setup.

**Comment by bradallred** [comment]
ok, I can just merge this for now and we can circle back. I dont have time right now either.

**Pull request merged**
