### PR TITLE
BG: disables mission pack button in menu when not installed

### LINKED ISSUE #758: BG: Ghost list of save games accessible from main menu
#### Bug description
I think I just clicked in too much haste and landed in some ghost area. For my BG, below the "Load Game" button, there is blank space. But actually you end up in an empty list of save games.

GemRB version: master

#### Steps to reproduce
1. Go to BG1 main menu.
2. Click the solo play button.
3. Click below the load button.

#### Expected behavior
Nothing should happen.

#### Screenshots
Demo:
<details>
  <summary></summary>

store

</details>

### PR DESCRIPTION
**Pull request by MarcelHB**
## Description
fixes #758 

## Checklist

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] I used the same coding style as the surrounding code 
- [x] I have tested the proposed changes
- [x] I extended the documentation, if necessary
- [x] The proposed change builds also on our build bots (check after submission)

### CODE REVIEW

**Comment by bradallred** [comment]
I think I have a preference to deleting unwanted controls because it keeps noise out of your way when debugging issues with the view hierarchy. I think it is odd to keep things around that we don't want.

**Comment by MarcelHB** [comment]
The HTML-history of mine wants to have two distinct buttons with `display: none` being toggled, but then this kind of recycling can be found across the scripts, so :shrug:

**Comment by lynxlynxlynx** [comment]
Deleting would require moving more code into the if block, but that's about it.

**Comment by bradallred** [comment]
it's not a dealbreaker.

why is it called `MoviesButton` tho?

**Comment by lynxlynxlynx** [comment]
That's its label on the first screen, nothing special.

**Comment by bradallred** [comment]
Sure, but is there a reason? it seems like it has nothing to do with "movies" and makes the code much less clear.

**Comment by lynxlynxlynx** [comment]
Yes, the second menu is not actually in a separate window, just everything gets relabelled and the callbacks changed.

**Comment by MarcelHB** [comment]
I can offer `PartTimeMoviesPartTimeMissionPackButton` without reorganizing the menu as a whole.

**Comment by chilvence** [comment]
I had a 1999 flashback. I think the button is actually just for 'movies' and then they hijack it for the mission pack when you install TOTSC.

**Comment by lynxlynxlynx** [comment]
It is for movies, but on on the main screen — this one is one level deeper, once you choose singleplayer.

**Comment by lynxlynxlynx** [comment]
So, since it's the same window, deleting would actually hurt.

**Pull request merged**
